# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste_btn_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Sequence
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(482, 220)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")

		self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
		self.tableWidget.setGeometry(QtCore.QRect(10, 10, 451, 192))
		self.tableWidget.setObjectName("tableWidget")

		# INDICA O NUMERO DE COLUNAS
		self.tableWidget.setColumnCount(2)

		# INDICA O NUMERO DE LINHAS
		self.tableWidget.setRowCount(2)

		
		# CRIA O FRAME PARA RECEBER OS BOTÕES
		self.frame_botoes = QtWidgets.QFrame(self.tableWidget)
		self.tableWidget.setCellWidget(1, 1, self.frame_botoes)

		# CRIA UM BOTÃO EDITAR DENTRO DO FRAME DE BOTÕES
		self.pushButton_editar_linha = QtWidgets.QPushButton(self.frame_botoes)
		self.pushButton_editar_linha.setObjectName("pushButton_editar_linha")

		# CRIA UM BOTÃO EXCLUIR DENTRO DO FRAME DE BOTÕES
		self.pushButton_excluir_linha = QtWidgets.QPushButton(self.frame_botoes)
		self.pushButton_excluir_linha.setObjectName("pushButton_excluir_linha")

		def clicou_editar():
			print('clicou editar')

		def clicou_excluir():
			print('clicou excluir')

		self.pushButton_editar_linha.clicked.connect(clicou_editar)

		self.pushButton_excluir_linha.clicked.connect(clicou_excluir)

		linha_1 = QtWidgets.QTableWidgetItem()
		self.tableWidget.setVerticalHeaderItem(0, linha_1)

		linha_2 = QtWidgets.QTableWidgetItem()
		self.tableWidget.setVerticalHeaderItem(1, linha_2)

		coluna_1 = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(0, coluna_1)

		coluna_2 = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(1, coluna_2)

		self.tableWidget.verticalHeader().setVisible(0)

		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

		# BOTÃO EDITAR DENTRO DA TABLEWIDGET
		self.pushButton_editar_linha.setText(_translate("", "Editar"))
		self.pushButton_editar_linha.setGeometry(QtCore.QRect(5,5,45,20))

		# BOTÃO EXCLUIR DENTRO DA TABLEWIDGET
		self.pushButton_excluir_linha.setText(_translate("", "Excluir"))
		self.pushButton_excluir_linha.setGeometry(QtCore.QRect(50,5,45,20))
		
		linha_1 = self.tableWidget.verticalHeaderItem(0)
		linha_1.setText(_translate("MainWindow", "linha 1"))
		
		linha_2 = self.tableWidget.verticalHeaderItem(1)
		linha_2.setText(_translate("MainWindow", "linha 2"))
		
		coluna_1 = self.tableWidget.horizontalHeaderItem(0)
		coluna_1.setText(_translate("MainWindow", "Coluna 1"))
		
		coluna_2 = self.tableWidget.horizontalHeaderItem(1)
		coluna_2.setText(_translate("MainWindow", "Coluna 2"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
