# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_pesquisar_orcamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_pesquisar_orcamento(object):
    def setupUi(self, tela_pesquisar_orcamento):
        tela_pesquisar_orcamento.setObjectName("tela_pesquisar_orcamento")
        tela_pesquisar_orcamento.resize(700, 425)
        self.centralwidget = QtWidgets.QWidget(tela_pesquisar_orcamento)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_pesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pesquisar.setGeometry(QtCore.QRect(370, 50, 75, 23))
        self.pushButton_pesquisar.setObjectName("pushButton_pesquisar")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 670, 260))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 350, 670, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 10, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(248, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(167, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(329, 10, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        tela_pesquisar_orcamento.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_pesquisar_orcamento)
        QtCore.QMetaObject.connectSlotsByName(tela_pesquisar_orcamento)
        tela_pesquisar_orcamento.setTabOrder(self.lineEdit, self.pushButton_pesquisar)
        tela_pesquisar_orcamento.setTabOrder(self.pushButton_pesquisar, self.tableWidget)
        tela_pesquisar_orcamento.setTabOrder(self.tableWidget, self.pushButton)
        tela_pesquisar_orcamento.setTabOrder(self.pushButton, self.pushButton_2)
        tela_pesquisar_orcamento.setTabOrder(self.pushButton_2, self.pushButton_3)
        tela_pesquisar_orcamento.setTabOrder(self.pushButton_3, self.pushButton_4)

    def retranslateUi(self, tela_pesquisar_orcamento):
        _translate = QtCore.QCoreApplication.translate
        tela_pesquisar_orcamento.setWindowTitle(_translate("tela_pesquisar_orcamento", "Pesquisar Orçamento"))
        self.label.setText(_translate("tela_pesquisar_orcamento", "PESQUISAR ORÇAMENTO:"))
        self.lineEdit.setToolTip(_translate("tela_pesquisar_orcamento", "Insira o nome do cliente ou o código do orçamento"))
        self.pushButton_pesquisar.setText(_translate("tela_pesquisar_orcamento", "Pesquisar"))
        self.pushButton_4.setText(_translate("tela_pesquisar_orcamento", "Cancelar"))
        self.pushButton_2.setText(_translate("tela_pesquisar_orcamento", "Editar"))
        self.pushButton.setText(_translate("tela_pesquisar_orcamento", "Visualizar"))
        self.pushButton_3.setText(_translate("tela_pesquisar_orcamento", "Excluir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_pesquisar_orcamento = QtWidgets.QMainWindow()
    ui = Ui_tela_pesquisar_orcamento()
    ui.setupUi(tela_pesquisar_orcamento)
    tela_pesquisar_orcamento.show()
    sys.exit(app.exec_())
