# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_menu_produtos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_menu_produtos(object):
    def setupUi(self, MainWindow_menu_produtos):
        MainWindow_menu_produtos.setObjectName("MainWindow_menu_produtos")
        MainWindow_menu_produtos.resize(1519, 899)
        MainWindow_menu_produtos.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget_menu_principal = QtWidgets.QWidget(MainWindow_menu_produtos)
        self.centralwidget_menu_principal.setObjectName("centralwidget_menu_principal")
        self.groupBox_linha_modular = QtWidgets.QGroupBox(self.centralwidget_menu_principal)
        self.groupBox_linha_modular.setGeometry(QtCore.QRect(20, 20, 561, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_linha_modular.setFont(font)
        self.groupBox_linha_modular.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_linha_modular.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_linha_modular.setFlat(False)
        self.groupBox_linha_modular.setCheckable(False)
        self.groupBox_linha_modular.setObjectName("groupBox_linha_modular")
        self.pushButton_vitro_modular_2f = QtWidgets.QPushButton(self.groupBox_linha_modular)
        self.pushButton_vitro_modular_2f.setGeometry(QtCore.QRect(20, 30, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_vitro_modular_2f.setFont(font)
        self.pushButton_vitro_modular_2f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 100, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_vitro_modular_2f.setObjectName("pushButton_vitro_modular_2f")
        self.pushButton_vitro_modular_4f = QtWidgets.QPushButton(self.groupBox_linha_modular)
        self.pushButton_vitro_modular_4f.setGeometry(QtCore.QRect(20, 90, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_vitro_modular_4f.setFont(font)
        self.pushButton_vitro_modular_4f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 100, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_vitro_modular_4f.setObjectName("pushButton_vitro_modular_4f")
        self.pushButton_veneziana_modular_3f = QtWidgets.QPushButton(self.groupBox_linha_modular)
        self.pushButton_veneziana_modular_3f.setGeometry(QtCore.QRect(290, 30, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_veneziana_modular_3f.setFont(font)
        self.pushButton_veneziana_modular_3f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 100, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_veneziana_modular_3f.setObjectName("pushButton_veneziana_modular_3f")
        self.pushButton_veneziana_modular_6f = QtWidgets.QPushButton(self.groupBox_linha_modular)
        self.pushButton_veneziana_modular_6f.setGeometry(QtCore.QRect(290, 90, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_veneziana_modular_6f.setFont(font)
        self.pushButton_veneziana_modular_6f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 100, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_veneziana_modular_6f.setObjectName("pushButton_veneziana_modular_6f")
        self.groupBox_vitro_linha_25 = QtWidgets.QGroupBox(self.centralwidget_menu_principal)
        self.groupBox_vitro_linha_25.setGeometry(QtCore.QRect(600, 20, 901, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_vitro_linha_25.setFont(font)
        self.groupBox_vitro_linha_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_vitro_linha_25.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_vitro_linha_25.setFlat(False)
        self.groupBox_vitro_linha_25.setCheckable(False)
        self.groupBox_vitro_linha_25.setObjectName("groupBox_vitro_linha_25")
        self.pushButton_vitro_linha25_2f = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_vitro_linha25_2f.setGeometry(QtCore.QRect(20, 30, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_vitro_linha25_2f.setFont(font)
        self.pushButton_vitro_linha25_2f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_vitro_linha25_2f.setObjectName("pushButton_vitro_linha25_2f")
        self.pushButton_vitro_linha25_4f = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_vitro_linha25_4f.setGeometry(QtCore.QRect(20, 90, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_vitro_linha25_4f.setFont(font)
        self.pushButton_vitro_linha25_4f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_vitro_linha25_4f.setObjectName("pushButton_vitro_linha25_4f")
        self.pushButton_veneziana_linha25_3f = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_veneziana_linha25_3f.setGeometry(QtCore.QRect(320, 30, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_veneziana_linha25_3f.setFont(font)
        self.pushButton_veneziana_linha25_3f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_veneziana_linha25_3f.setObjectName("pushButton_veneziana_linha25_3f")
        self.pushButton_veneziana_linha25_6f = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_veneziana_linha25_6f.setGeometry(QtCore.QRect(320, 90, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_veneziana_linha25_6f.setFont(font)
        self.pushButton_veneziana_linha25_6f.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_veneziana_linha25_6f.setObjectName("pushButton_veneziana_linha25_6f")
        self.pushButton_vitro_linha25_2f_2 = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_vitro_linha25_2f_2.setGeometry(QtCore.QRect(620, 30, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_vitro_linha25_2f_2.setFont(font)
        self.pushButton_vitro_linha25_2f_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_vitro_linha25_2f_2.setObjectName("pushButton_vitro_linha25_2f_2")
        self.pushButton_veneziana_linha25_3f_2 = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_veneziana_linha25_3f_2.setGeometry(QtCore.QRect(20, 150, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_veneziana_linha25_3f_2.setFont(font)
        self.pushButton_veneziana_linha25_3f_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_veneziana_linha25_3f_2.setObjectName("pushButton_veneziana_linha25_3f_2")
        self.pushButton_vitro_linha25_4f_2 = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_vitro_linha25_4f_2.setGeometry(QtCore.QRect(620, 90, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_vitro_linha25_4f_2.setFont(font)
        self.pushButton_vitro_linha25_4f_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_vitro_linha25_4f_2.setObjectName("pushButton_vitro_linha25_4f_2")
        self.pushButton_veneziana_linha25_6f_2 = QtWidgets.QPushButton(self.groupBox_vitro_linha_25)
        self.pushButton_veneziana_linha25_6f_2.setGeometry(QtCore.QRect(320, 150, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_veneziana_linha25_6f_2.setFont(font)
        self.pushButton_veneziana_linha25_6f_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 220, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_veneziana_linha25_6f_2.setObjectName("pushButton_veneziana_linha25_6f_2")
        self.groupBox_porta_balcao_linha25 = QtWidgets.QGroupBox(self.centralwidget_menu_principal)
        self.groupBox_porta_balcao_linha25.setGeometry(QtCore.QRect(430, 280, 401, 641))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_porta_balcao_linha25.setFont(font)
        self.groupBox_porta_balcao_linha25.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_porta_balcao_linha25.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_porta_balcao_linha25.setFlat(False)
        self.groupBox_porta_balcao_linha25.setCheckable(False)
        self.groupBox_porta_balcao_linha25.setObjectName("groupBox_porta_balcao_linha25")
        self.pushButton_pt_balcao_2f_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_2f_linha25.setGeometry(QtCore.QRect(20, 30, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_2f_linha25.setFont(font)
        self.pushButton_pt_balcao_2f_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_2f_linha25.setObjectName("pushButton_pt_balcao_2f_linha25")
        self.pushButton_pt_balcao_travessa_2f_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_travessa_2f_linha25.setGeometry(QtCore.QRect(20, 90, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_travessa_2f_linha25.setFont(font)
        self.pushButton_pt_balcao_travessa_2f_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_travessa_2f_linha25.setObjectName("pushButton_pt_balcao_travessa_2f_linha25")
        self.pushButton_pt_balcao_4f_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_4f_linha25.setGeometry(QtCore.QRect(20, 150, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_4f_linha25.setFont(font)
        self.pushButton_pt_balcao_4f_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_4f_linha25.setObjectName("pushButton_pt_balcao_4f_linha25")
        self.pushButton_pt_balcao_travessa_4f_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_travessa_4f_linha25.setGeometry(QtCore.QRect(20, 210, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_travessa_4f_linha25.setFont(font)
        self.pushButton_pt_balcao_travessa_4f_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_travessa_4f_linha25.setObjectName("pushButton_pt_balcao_travessa_4f_linha25")
        self.pushButton_pt_balcao_venez_3f_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_venez_3f_linha25.setGeometry(QtCore.QRect(20, 390, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_venez_3f_linha25.setFont(font)
        self.pushButton_pt_balcao_venez_3f_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_venez_3f_linha25.setObjectName("pushButton_pt_balcao_venez_3f_linha25")
        self.pushButton_pt_balcao_3planos_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_3planos_linha25.setGeometry(QtCore.QRect(20, 270, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_3planos_linha25.setFont(font)
        self.pushButton_pt_balcao_3planos_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_3planos_linha25.setObjectName("pushButton_pt_balcao_3planos_linha25")
        self.pushButton_pt_balcao_venez_6f_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_venez_6f_linha25.setGeometry(QtCore.QRect(20, 450, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_venez_6f_linha25.setFont(font)
        self.pushButton_pt_balcao_venez_6f_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_venez_6f_linha25.setObjectName("pushButton_pt_balcao_venez_6f_linha25")
        self.pushButton_pt_balcao_3planos_travessa_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balcao_3planos_travessa_linha25.setGeometry(QtCore.QRect(20, 330, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balcao_3planos_travessa_linha25.setFont(font)
        self.pushButton_pt_balcao_3planos_travessa_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balcao_3planos_travessa_linha25.setObjectName("pushButton_pt_balcao_3planos_travessa_linha25")
        self.pushButton_pt_balc_3planos_vdint_linha25 = QtWidgets.QPushButton(self.groupBox_porta_balcao_linha25)
        self.pushButton_pt_balc_3planos_vdint_linha25.setGeometry(QtCore.QRect(20, 510, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_balc_3planos_vdint_linha25.setFont(font)
        self.pushButton_pt_balc_3planos_vdint_linha25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 153, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_balc_3planos_vdint_linha25.setObjectName("pushButton_pt_balc_3planos_vdint_linha25")
        self.groupBox_linha14_max_basc = QtWidgets.QGroupBox(self.centralwidget_menu_principal)
        self.groupBox_linha14_max_basc.setGeometry(QtCore.QRect(20, 180, 561, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_linha14_max_basc.setFont(font)
        self.groupBox_linha14_max_basc.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_linha14_max_basc.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_linha14_max_basc.setFlat(False)
        self.groupBox_linha14_max_basc.setCheckable(False)
        self.groupBox_linha14_max_basc.setObjectName("groupBox_linha14_max_basc")
        self.pushButton_basculante_linha14 = QtWidgets.QPushButton(self.groupBox_linha14_max_basc)
        self.pushButton_basculante_linha14.setGeometry(QtCore.QRect(20, 30, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_basculante_linha14.setFont(font)
        self.pushButton_basculante_linha14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_basculante_linha14.setObjectName("pushButton_basculante_linha14")
        self.pushButton_maximar_linha14 = QtWidgets.QPushButton(self.groupBox_linha14_max_basc)
        self.pushButton_maximar_linha14.setGeometry(QtCore.QRect(300, 30, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_maximar_linha14.setFont(font)
        self.pushButton_maximar_linha14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_maximar_linha14.setObjectName("pushButton_maximar_linha14")
        self.groupBox_porta_giro = QtWidgets.QGroupBox(self.centralwidget_menu_principal)
        self.groupBox_porta_giro.setGeometry(QtCore.QRect(20, 280, 391, 641))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_porta_giro.setFont(font)
        self.groupBox_porta_giro.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_porta_giro.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_porta_giro.setFlat(False)
        self.groupBox_porta_giro.setCheckable(False)
        self.groupBox_porta_giro.setObjectName("groupBox_porta_giro")
        self.pushButton_pt_giro_palheta = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_palheta.setGeometry(QtCore.QRect(20, 30, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_palheta.setFont(font)
        self.pushButton_pt_giro_palheta.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_palheta.setObjectName("pushButton_pt_giro_palheta")
        self.pushButton_pt_giro_social_pl = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_social_pl.setGeometry(QtCore.QRect(20, 90, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_social_pl.setFont(font)
        self.pushButton_pt_giro_social_pl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_social_pl.setObjectName("pushButton_pt_giro_social_pl")
        self.pushButton_pt_gio_social_lb = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_gio_social_lb.setGeometry(QtCore.QRect(20, 210, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_gio_social_lb.setFont(font)
        self.pushButton_pt_gio_social_lb.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_gio_social_lb.setObjectName("pushButton_pt_gio_social_lb")
        self.pushButton_pt_giro_basculante_lb = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_basculante_lb.setGeometry(QtCore.QRect(20, 270, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_basculante_lb.setFont(font)
        self.pushButton_pt_giro_basculante_lb.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_basculante_lb.setObjectName("pushButton_pt_giro_basculante_lb")
        self.pushButton_pt_giro_lb_puxador_friso = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_lb_puxador_friso.setGeometry(QtCore.QRect(20, 450, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_lb_puxador_friso.setFont(font)
        self.pushButton_pt_giro_lb_puxador_friso.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_lb_puxador_friso.setObjectName("pushButton_pt_giro_lb_puxador_friso")
        self.pushButton_pt_giro_lb_macaneta = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_lb_macaneta.setGeometry(QtCore.QRect(20, 330, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_lb_macaneta.setFont(font)
        self.pushButton_pt_giro_lb_macaneta.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_lb_macaneta.setObjectName("pushButton_pt_giro_lb_macaneta")
        self.pushButton_pt_giro_lb_puxador_vidro = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_lb_puxador_vidro.setGeometry(QtCore.QRect(20, 510, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_lb_puxador_vidro.setFont(font)
        self.pushButton_pt_giro_lb_puxador_vidro.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_lb_puxador_vidro.setObjectName("pushButton_pt_giro_lb_puxador_vidro")
        self.pushButton_pt_giro_lb_puxador = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_lb_puxador.setGeometry(QtCore.QRect(20, 390, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_lb_puxador.setFont(font)
        self.pushButton_pt_giro_lb_puxador.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_lb_puxador.setObjectName("pushButton_pt_giro_lb_puxador")
        self.pushButton_pt_giro_basculante_pl = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_basculante_pl.setGeometry(QtCore.QRect(20, 150, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_basculante_pl.setFont(font)
        self.pushButton_pt_giro_basculante_pl.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_basculante_pl.setObjectName("pushButton_pt_giro_basculante_pl")
        self.pushButton_pt_giro_lb_puxador_vidro_friso = QtWidgets.QPushButton(self.groupBox_porta_giro)
        self.pushButton_pt_giro_lb_puxador_vidro_friso.setGeometry(QtCore.QRect(20, 570, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_giro_lb_puxador_vidro_friso.setFont(font)
        self.pushButton_pt_giro_lb_puxador_vidro_friso.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(238, 120, 17, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_giro_lb_puxador_vidro_friso.setObjectName("pushButton_pt_giro_lb_puxador_vidro_friso")
        self.groupBox_porta_pivotante = QtWidgets.QGroupBox(self.centralwidget_menu_principal)
        self.groupBox_porta_pivotante.setGeometry(QtCore.QRect(850, 280, 401, 641))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_porta_pivotante.setFont(font)
        self.groupBox_porta_pivotante.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_porta_pivotante.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_porta_pivotante.setFlat(False)
        self.groupBox_porta_pivotante.setCheckable(False)
        self.groupBox_porta_pivotante.setObjectName("groupBox_porta_pivotante")
        self.pushButton_pt_piv_lb_puxador = QtWidgets.QPushButton(self.groupBox_porta_pivotante)
        self.pushButton_pt_piv_lb_puxador.setGeometry(QtCore.QRect(20, 30, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_piv_lb_puxador.setFont(font)
        self.pushButton_pt_piv_lb_puxador.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(215, 15, 15, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_piv_lb_puxador.setObjectName("pushButton_pt_piv_lb_puxador")
        self.pushButton_pt_piv_lb_puxador_friso = QtWidgets.QPushButton(self.groupBox_porta_pivotante)
        self.pushButton_pt_piv_lb_puxador_friso.setGeometry(QtCore.QRect(20, 90, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_piv_lb_puxador_friso.setFont(font)
        self.pushButton_pt_piv_lb_puxador_friso.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(215, 15, 15, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_piv_lb_puxador_friso.setObjectName("pushButton_pt_piv_lb_puxador_friso")
        self.pushButton_pt_piv_lb_puxador_vidro = QtWidgets.QPushButton(self.groupBox_porta_pivotante)
        self.pushButton_pt_piv_lb_puxador_vidro.setGeometry(QtCore.QRect(20, 150, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_piv_lb_puxador_vidro.setFont(font)
        self.pushButton_pt_piv_lb_puxador_vidro.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(215, 15, 15, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_piv_lb_puxador_vidro.setObjectName("pushButton_pt_piv_lb_puxador_vidro")
        self.pushButton_pt_piv_lb_puxador_friso_vidro = QtWidgets.QPushButton(self.groupBox_porta_pivotante)
        self.pushButton_pt_piv_lb_puxador_friso_vidro.setGeometry(QtCore.QRect(20, 210, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_pt_piv_lb_puxador_friso_vidro.setFont(font)
        self.pushButton_pt_piv_lb_puxador_friso_vidro.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(215, 15, 15, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_pt_piv_lb_puxador_friso_vidro.setObjectName("pushButton_pt_piv_lb_puxador_friso_vidro")
        MainWindow_menu_produtos.setCentralWidget(self.centralwidget_menu_principal)

        self.retranslateUi(MainWindow_menu_produtos)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_menu_produtos)

    def retranslateUi(self, MainWindow_menu_produtos):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_menu_produtos.setWindowTitle(_translate("MainWindow_menu_produtos", ".:: PERFILARE ::. - Meu de Produtos"))
        self.groupBox_linha_modular.setTitle(_translate("MainWindow_menu_produtos", "LINHA MODULAR"))
        self.pushButton_vitro_modular_2f.setText(_translate("MainWindow_menu_produtos", "VITRO 2 FOLHAS - LINHA MODULAR"))
        self.pushButton_vitro_modular_4f.setText(_translate("MainWindow_menu_produtos", "VITRO 4 FOLHAS - LINHA MODULAR"))
        self.pushButton_veneziana_modular_3f.setText(_translate("MainWindow_menu_produtos", "VENEZIANA 3 FOLHAS - LINHA MODULAR"))
        self.pushButton_veneziana_modular_6f.setText(_translate("MainWindow_menu_produtos", "VENEZIANA 6 FOLHAS - LINHA MODULAR"))
        self.groupBox_vitro_linha_25.setTitle(_translate("MainWindow_menu_produtos", "VITROS LINHA 25"))
        self.pushButton_vitro_linha25_2f.setText(_translate("MainWindow_menu_produtos", "VITRO 2 FOLHAS - LINHA 25"))
        self.pushButton_vitro_linha25_4f.setText(_translate("MainWindow_menu_produtos", "VITRO 4 FOLHAS - LINHA 25"))
        self.pushButton_veneziana_linha25_3f.setText(_translate("MainWindow_menu_produtos", "VENEZIANA 3 FOLHAS - LINHA 25"))
        self.pushButton_veneziana_linha25_6f.setText(_translate("MainWindow_menu_produtos", "VENEZIANA 6 FOLHAS - LINHA 25"))
        self.pushButton_vitro_linha25_2f_2.setText(_translate("MainWindow_menu_produtos", "VITRO TRAVESSA 2 FOLHAS - LINHA 25"))
        self.pushButton_veneziana_linha25_3f_2.setText(_translate("MainWindow_menu_produtos", "VITRO 3 PLANOS - LINHA 25"))
        self.pushButton_vitro_linha25_4f_2.setText(_translate("MainWindow_menu_produtos", "VITRO TRAVESSA 4 FOLHAS - LINHA 25"))
        self.pushButton_veneziana_linha25_6f_2.setText(_translate("MainWindow_menu_produtos", "VITRO TRAVESSA 3 PLANOS - LINHA 25"))
        self.groupBox_porta_balcao_linha25.setTitle(_translate("MainWindow_menu_produtos", "PORTA BALCÃO - LINHA 25"))
        self.pushButton_pt_balcao_2f_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO 2 FOLHAS - LINHA 25"))
        self.pushButton_pt_balcao_travessa_2f_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO TRAVESSA 2 FOLHAS - LINHA 25"))
        self.pushButton_pt_balcao_4f_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO 4 FOLHAS - LINHA 25"))
        self.pushButton_pt_balcao_travessa_4f_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO TRAVESSA 4 FOLHAS - LINHA 25"))
        self.pushButton_pt_balcao_venez_3f_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO VENEZIANA 3 FOLHAS - LINHA 25"))
        self.pushButton_pt_balcao_3planos_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO 3 PLANOS - LINHA 25"))
        self.pushButton_pt_balcao_venez_6f_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO VENEZIANA 6 FOLHAS  - LINHA 25"))
        self.pushButton_pt_balcao_3planos_travessa_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO TRAVESSA 3 PLANOS - LINHA 25"))
        self.pushButton_pt_balc_3planos_vdint_linha25.setText(_translate("MainWindow_menu_produtos", "PORTA BALCÃO VIDRO INTEIRO 3 PLANOS - LINHA 25"))
        self.groupBox_linha14_max_basc.setTitle(_translate("MainWindow_menu_produtos", "LINHA 14"))
        self.pushButton_basculante_linha14.setText(_translate("MainWindow_menu_produtos", "BASCULANTE - LINHA 14"))
        self.pushButton_maximar_linha14.setText(_translate("MainWindow_menu_produtos", "MAXIM-AR - LINHA 14"))
        self.groupBox_porta_giro.setTitle(_translate("MainWindow_menu_produtos", "PORTAS DE GIRO"))
        self.pushButton_pt_giro_palheta.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - COM PALHETAS"))
        self.pushButton_pt_giro_social_pl.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - SOCIAL COM POSTIGO(PALHETAS)"))
        self.pushButton_pt_gio_social_lb.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - SOCIAL COM POSTIGO(LAMBRIL)"))
        self.pushButton_pt_giro_basculante_lb.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - COM BASCULANTES (LAMBRIL)"))
        self.pushButton_pt_giro_lb_puxador_friso.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - LAMBRIL PUXADOR E FRISO"))
        self.pushButton_pt_giro_lb_macaneta.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - LAMBRIL COM MAÇANETA"))
        self.pushButton_pt_giro_lb_puxador_vidro.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - LAMBRIL PUXADOR E VIDRO"))
        self.pushButton_pt_giro_lb_puxador.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - LAMBRIL COM PUXADOR"))
        self.pushButton_pt_giro_basculante_pl.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - COM BASCULANTES (PALHETAS)"))
        self.pushButton_pt_giro_lb_puxador_vidro_friso.setText(_translate("MainWindow_menu_produtos", "PORTA DE GIRO - LAMBRIL PUXADOR VIDRO E FRISO"))
        self.groupBox_porta_pivotante.setTitle(_translate("MainWindow_menu_produtos", "PORTAS PIVOTANTES"))
        self.pushButton_pt_piv_lb_puxador.setText(_translate("MainWindow_menu_produtos", "PORTA PIVOTANTE COM LAMBRIL E PUXADOR"))
        self.pushButton_pt_piv_lb_puxador_friso.setText(_translate("MainWindow_menu_produtos", "PORTA PIVOTANTE COM LAMBRIL PUXADOR E FRISO"))
        self.pushButton_pt_piv_lb_puxador_vidro.setText(_translate("MainWindow_menu_produtos", "PORTA PIVOTANTE COM LAMBRIL PUXADOR E VIDRO"))
        self.pushButton_pt_piv_lb_puxador_friso_vidro.setText(_translate("MainWindow_menu_produtos", "PORTA PIVOTANTE COM LAMBRIL PUXADO FRISO E VIDRO"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow_menu_produtos = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow_menu_produtos()
#     ui.setupUi(MainWindow_menu_produtos)
#     MainWindow_menu_produtos.show()
#     sys.exit(app.exec_())
